"""Wire schemas: the contracts LLM output must satisfy.

These are deliberately separate from the domain models (ADR-011). The
model never sees or invents QAOps IDs - wire objects are ID-less, and
stage code assigns REQ-*/BR-* IDs deterministically (ADR-001) while
mapping wire objects into the strict domain models. The only IDs a wire
object may contain are *references* to IDs the prompt supplied, and
stage code verifies every reference against the known set.

All wire schemas forbid unknown fields (ADR-003): a hallucinated field
fails validation inside generate_structured() and triggers the repair
retry loop.
"""

from pydantic import BaseModel, ConfigDict, Field

from qaops.models.enums import GapSeverity, Priority, ScenarioCategory, TestType


class _WireModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ExtractedRequirement(_WireModel):
    """One requirement as extracted by the model - no ID."""

    title: str = Field(min_length=1)
    description: str = Field(min_length=1)
    source_excerpt: str = ""
    actors: list[str] = Field(default_factory=list)
    inputs: list[str] = Field(default_factory=list)
    outputs: list[str] = Field(default_factory=list)
    validations: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)


class RequirementExtraction(_WireModel):
    """Top-level analyzer output."""

    requirements: list[ExtractedRequirement] = Field(default_factory=list)


class ExtractedRule(_WireModel):
    """One business rule referencing a requirement ID supplied in the prompt."""

    requirement_id: str = Field(min_length=1)
    rule: str = Field(min_length=1)
    source_excerpt: str = ""


class RuleExtraction(_WireModel):
    """Top-level rule-extractor output."""

    rules: list[ExtractedRule] = Field(default_factory=list)


class ExtractedGap(_WireModel):
    """One ambiguity/gap found in the requirements."""

    description: str = Field(min_length=1)
    severity: GapSeverity = GapSeverity.MAJOR
    requirement_id: str | None = None
    suggested_question: str = ""


class GapExtraction(_WireModel):
    """Top-level gap-analyzer output."""

    gaps: list[ExtractedGap] = Field(default_factory=list)


class ExtractedScenario(_WireModel):
    """One test scenario as generated by the model - no SC-* ID.

    requirement_ids are references to REQ-* IDs supplied in the prompt;
    stage code verifies them against the known set. category must be one
    of the ScenarioCategory enum values - anything else fails validation
    and triggers the repair retry loop.
    """

    title: str = Field(min_length=1)
    description: str = ""
    category: ScenarioCategory
    requirement_ids: list[str] = Field(min_length=1)


class ScenarioExtraction(_WireModel):
    """Top-level scenario-generator output."""

    scenarios: list[ExtractedScenario] = Field(default_factory=list)


class ExtractedTestStep(_WireModel):
    """One test step as generated by the model - NO step number.

    Steps arrive as an ordered list; stage code assigns numbers 1..N
    from list order (ADR-014), so mis-numbered steps cannot exist.
    """

    action: str = Field(min_length=1)
    expected: str = ""


class ExtractedTestCase(_WireModel):
    """One manual test case as generated by the model - no TC-* ID.

    scenario_id and requirement_ids are references to IDs supplied in
    the prompt; stage code verifies both against the known sets.
    priority and test_type are validated against the enums, so invalid
    values trigger the repair retry loop.
    """

    scenario_id: str = Field(min_length=1)
    requirement_ids: list[str] = Field(min_length=1)
    module: str = ""
    feature: str = ""
    title: str = Field(min_length=1)
    objective: str = ""
    preconditions: list[str] = Field(default_factory=list)
    test_data: dict[str, str] = Field(default_factory=dict)
    steps: list[ExtractedTestStep] = Field(min_length=1)
    expected_result: str = Field(min_length=1)
    priority: Priority = Priority.MEDIUM
    test_type: TestType = TestType.FUNCTIONAL
    tags: list[str] = Field(default_factory=list)


class TestCaseExtraction(_WireModel):
    """Top-level test-case-generator output."""

    test_cases: list[ExtractedTestCase] = Field(default_factory=list)
